coverage:
  status:
    project:
      core:
        target: auto
        flags:
          - core
      utils:
        target: auto
        flags:
          - utils
flags:
  core:
    paths:
      - core.lcov
    carryforward: true
  utils:
    paths:
      - utils.lcov
    carryforward: true
